version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: meraki
       POSTGRES_DB: meraki
     ports:
       - 5437:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
